name:CI/CD is easy
on:
push:
brances:
-master
-dev

jobs:
buid:
runs-on: ubuntu-latest
steps:
-uses: actions/set-node@v1
with:
node-version 12
-run:npm ci
-run:npm test
-run:npm run build
-run:npm run deploy
