name: Frontend CI/CD
on:
  push:
    branches:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
         node-version: '14'
    - name: Install packages
      run: npm install
    - name: Build Next.js Application
      run: npm run build
    - name: Deploy to Production
      uses: some-deployment-action-here
      with:
         name: production
         path: ./path-to-build-folder
    - name: Run Tests
      run: npm test





